In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],
             [2,4 ,"5"]], dtype= np.int32 )
print(a)
print(type(a))
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a[0][0].dtype)

[[1 2 3]
 [2 4 5]]
<class 'numpy.ndarray'>
(2, 3)
2
6
int32
int32


In [4]:
a = np.full((2, 3), 12)
print(a, "\n")

a = np.zeros((2, 5))
print(a , "\n")

print(a.T)

a = np.ones((5, 5))
print(a)

a = np.empty((5, 5))
print(a)

[[12 12 12]
 [12 12 12]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
print(np.sqrt(2))
print(np.array([1])/0)

1.4142135623730951
[inf]


C:\Users\Mega Store\AppData\Local\Temp\ipykernel_7176\2394361447.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.array([1])/0)


In [6]:
print(np.pi)
print(np.sum(np.ones((12,3))))
print(np.e)

3.141592653589793
36.0
2.718281828459045


In [7]:
print(np.random.normal(loc = 170 , scale= 15   ,size=(5,10)))

[[144.3920825  165.01262281 167.15083194 144.76594239 165.33703001
  172.01004608 159.4639071  171.70334446 175.43664783 153.31733754]
 [156.34815686 156.19445874 163.7548196  170.10431461 204.74478394
  150.14509263 153.08914939 166.20461998 144.62142979 149.9740911 ]
 [170.42528915 188.75287499 169.78325333 152.16725622 172.74723945
  176.12781951 161.68078316 163.01810389 185.15145049 169.39690273]
 [164.61719995 166.88096178 167.71541787 169.55475721 155.12032748
  165.70281117 158.85528401 182.67861662 157.15350609 183.7294886 ]
 [146.81651465 189.49029074 167.96806009 159.76709871 150.88387027
  180.28775104 184.93449946 167.432631   192.85020743 163.56166954]]


In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame(np.random.normal(loc = 170 , scale= 15   ,size=(5,10)))

In [10]:
df

0           1           2           3           4           5  \
0  174.295613  184.874985  181.718273  153.420153  170.690402  153.275544   
1  170.827756  148.098028  189.154206  165.909007  176.063127  148.635203   
2  164.909070  162.783041  167.144793  183.006709  167.411617  178.784264   
3  175.563265  174.308984  168.223603  162.266081  158.251195  179.553845   
4  177.029059  167.828471  189.030123  161.908906  154.721780  183.678556   

            6           7           8           9  
0  193.716363  167.250776  162.708546  145.800997  
1  164.554011  180.909726  168.506145  183.547958  
2  176.297940  186.711538  158.813389  152.827058  
3  187.723980  160.777158  163.325041  200.918092  
4  148.711155  159.852425  178.273784  178.812643

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       5 non-null      float64
 1   1       5 non-null      float64
 2   2       5 non-null      float64
 3   3       5 non-null      float64
 4   4       5 non-null      float64
 5   5       5 non-null      float64
 6   6       5 non-null      float64
 7   7       5 non-null      float64
 8   8       5 non-null      float64
 9   9       5 non-null      float64
dtypes: float64(10)
memory usage: 532.0 bytes


In [12]:
df.describe()

0           1           2           3           4           5  \
count    5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   
mean   172.524953  167.578702  179.054200  165.302171  165.427624  168.785482   
std      4.835693   13.665792   10.813906   10.905656    8.815657   16.464575   
min    164.909070  148.098028  167.144793  153.420153  154.721780  148.635203   
25%    170.827756  162.783041  168.223603  161.908906  158.251195  153.275544   
50%    174.295613  167.828471  181.718273  162.266081  167.411617  178.784264   
75%    175.563265  174.308984  189.030123  165.909007  170.690402  179.553845   
max    177.029059  184.874985  189.154206  183.006709  176.063127  183.678556   

                6           7           8           9  
count    5.000000    5.000000    5.000000    5.000000  
mean   174.200690  171.100325  166.325381  172.381350  
std     18.103274   12.122669    7.517207   22.744702  
min    148.711155  159.852425  158.813389  145.800997  
25%    164.554011  160.777158  162.708546  152.827058  
50%    176.297940  167.250776  163.325041  178.812643  
75%    187.723980  180.909726  168.506145  183.547958  
max    193.716363  186.711538  178.273784  200.918092

In [13]:
df.shape

(5, 10)

In [1]:
import torch